---
title: "R Notebook"
output: html_notebook
---

## Load data


```{r}
data <- read.table("~/Téléchargements/mixtcomp-example.csv", sep = ";", header = TRUE)
head(data)
```


## Clustering with RMixtComp


```{r}
library(RMixtComp)
```


Define the distribution used for each variable
```{r}
model <- list(Age = "Gaussian", Wt = "Gaussian", PF = "Multinomial", 
              HX = "Multinomial", SBP = "Gaussian", DBP = "Gaussian", 
              EKG = "Multinomial", HG = "Gaussian", SZ = "Gaussian", 
              SG = "Gaussian", AP = "Gaussian", BM = "Multinomial")
```


Define the SEM algorithm's parameters
```{r}
algo <- list(nbBurnInIter = 50,
       nbIter = 100,
       nbGibbsBurnInIter = 100,
       nbGibbsIter = 100,
       nInitPerClass = floor(nrow(data)/2),
       nSemTry = 5,
       confidenceLevel = 0.95,
       ratioStableCriterion = 0.99,
       nStableCriterion = 10)
```


```{r}
res <- mixtCompLearn(data, model, algo, nClass = 1:8, criterion = "ICL", nRun = 3, nCore = 1)
```



## Criterion

```{r}
plotCrit(res, pkg = "plotly")
```


Choose the number of classes:
```{r}
K <- 3
resK <- extractMixtCompObject(res, K)
```


### Variables


```{r}
plotDiscrimVar(resK, pkg = "plotly")
```



```{r}
variable <- "SG"
```

```{r}
plotDataBoxplot(resK, variable, grl = TRUE, pkg = "plotly")
```


### Classes


```{r}
plotProportion(resK, pkg = "plotly")
```
```{r}
heatmapClass(resK)
```


```{r}
plotDiscrimVar(resK, class = 2, pkg = "plotly")
```



```{r}
plotDataBoxplot(resK, variable, class = 2, grl = TRUE, pkg = "plotly")
```




### Probabilities

```{r}
heatmapTikSorted(resK)
```



### Advanced

```{r}
library(ClusVis)
```


```{r}
logTik <- getTik(resK, log = TRUE)
prop <- getProportion(resK)
resVisu <- clusvis(logTik, prop)
```


```{r}
plotDensityClusVisu(resVisu, add.obs = TRUE)
```


```{r}
plotDensityClusVisu(resVisu, add.obs = FALSE)
```